version: '3.9'

services:
  redis:
    image: redis:alpine
    hostname: redis
    command: redis-server 
      --maxclients 500
      --tcp-keepalive 60 
      --timeout 300
      --maxmemory 800mb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
      --slowlog-log-slower-than 10000
      --slowlog-max-len 512
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - web
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  pgbouncer:
    image: edoburu/pgbouncer:v1.24.1-p1
    hostname: pgbouncer
    env_file: [.env]          # ← single file; comment-toggle dev vs prod
    environment:
      # ── where PgBouncer should forward connections ────────────────────
      - "DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
      # ── pool tuning ───────────────────────────────────────────────────
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=200              # Increased for multiple workers
      - DEFAULT_POOL_SIZE=40             # Increased from 18 to handle worker load
      - RESERVE_POOL_SIZE=5              # Increased reserve pool
      - RESERVE_POOL_TIMEOUT=10          # Increased timeout
      - QUERY_WAIT_TIMEOUT=60            # Increased from 30s
      - IGNORE_STARTUP_PARAMETERS=extra_float_digits
      - IDLE_TRANSACTION_TIMEOUT=30      # Increased from 10s
      - CLIENT_IDLE_TIMEOUT=120          # Increased from 60s
      - QUERY_TIMEOUT=60                 # Increased from 30s
      - SERVER_IDLE_TIMEOUT=600          # Increased from 300s
      - SERVER_LIFETIME=7200             # Increased from 3600s
      # ── upstream TLS & auth (left blank/disabled in dev .env) ─────────
      - PGBOUNCER_SERVER_TLS_SSLMODE=${SERVER_TLS_SSLMODE:-disable}
      - PGBOUNCER_SERVER_TLS_CA_FILE=${SERVER_TLS_CA_FILE:-}
      - PGBOUNCER_AUTH_TYPE=${AUTH_TYPE:-trust}
      # ── listener (PgBouncer ⇆ your apps) ──────────────────────────────
      - PGBOUNCER_CLIENT_TLS_SSLMODE=disable     # local traffic, no need for TLS
    # dev: mounts system CA bundle; prod: mounts do-ca.pem
    volumes:
      - ${SERVER_TLS_CA_FILE:-/etc/ssl/certs/ca-certificates.crt}:/etc/ssl/do-ca.pem:ro
    ports: ["6432:5432"]  # ← Map internal 5432 to external 6432
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-p", "5432", "-U", "${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [web]
    extra_hosts:
      - "host.docker.internal:host-gateway"

  celery-worker:
    build:
      context: ./Discord-Bot-WebUI
      dockerfile: Dockerfile.webui
    command: python celery_worker.py
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./Discord-Bot-WebUI:/app
      - celery_data:/tmp/celery
    healthcheck:
      test: ["CMD", "python", "healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      redis:
        condition: service_healthy
      pgbouncer:
        condition: service_healthy
    networks:
      - web
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      
  celery-player-sync-worker:
    build:
      context: ./Discord-Bot-WebUI
      dockerfile: Dockerfile.webui
    command: python celery_player_sync_worker.py
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./Discord-Bot-WebUI:/app
      - celery_sync_data:/tmp/celery_sync
    healthcheck:
      test: ["CMD", "python", "healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      redis:
        condition: service_healthy
      pgbouncer:
        condition: service_healthy
    networks:
      - web
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 300M

  celery-live-reporting-worker:
    build:
      context: ./Discord-Bot-WebUI
      dockerfile: Dockerfile.webui
    command: python celery_live_reporting_worker.py
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./Discord-Bot-WebUI:/app
      - celery_live_data:/tmp/celery_live
    healthcheck:
      test: ["CMD", "python", "healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      redis:
        condition: service_healthy
      pgbouncer:
        condition: service_healthy
    networks:
      - web
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 300M
      
  celery-discord-worker:
    build:
      context: ./Discord-Bot-WebUI
      dockerfile: Dockerfile.webui
    command: python celery_discord_worker.py
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./Discord-Bot-WebUI:/app
      - celery_live_data:/tmp/celery_live
    healthcheck:
      test: ["CMD", "python", "healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      redis:
        condition: service_healthy
      pgbouncer:
        condition: service_healthy
    networks:
      - web
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 600M  # Increase to accommodate 2 workers * 250MB each + overhead
        reservations:
          memory: 300M      

  celery-enterprise-rsvp-worker:
    build:
      context: ./Discord-Bot-WebUI
      dockerfile: Dockerfile.webui
    command: python celery_enterprise_rsvp_worker.py
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - REDIS_URL=redis://redis:6379/0
      - CELERY_WORKER=1  # Prevent Flask initialization in worker
    volumes:
      - ./Discord-Bot-WebUI:/app
      - celery_enterprise_data:/tmp/celery_enterprise
    healthcheck:
      test: ["CMD", "python", "healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      redis:
        condition: service_healthy
      pgbouncer:
        condition: service_healthy
    networks:
      - web
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 200M

  celery-beat:
    build:
      context: ./Discord-Bot-WebUI
      dockerfile: Dockerfile.webui
    command: >
      sh -c "rm -f /tmp/celerybeat/celerybeat.pid &&
      python celery_beat.py -s /tmp/celerybeat/celerybeat-schedule"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./Discord-Bot-WebUI:/app
      - celery_beat_data:/tmp/celerybeat
    healthcheck:
      test: ["CMD", "python", "healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      redis:
        condition: service_healthy
      pgbouncer:
        condition: service_healthy
    networks:
      - web
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 300M

  webui:
    build:
      context: ./Discord-Bot-WebUI
      dockerfile: Dockerfile.webui
    command: >
      sh -c "python build_assets.py &&
      gunicorn
      --worker-class eventlet
      --workers 1
      --bind 0.0.0.0:5000
      --log-level info
      --access-logfile -
      --error-logfile -
      --timeout 120
      --graceful-timeout 120
      --keep-alive 65
      --worker-connections 1000
      --max-requests 1000
      --max-requests-jitter 50
      --name webui
      wsgi:application"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - EVENTLET_NO_GREENDNS=yes
      - PYTHONPATH=/app
      - FLASK_DEBUG=1
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    volumes:
      - ./Discord-Bot-WebUI:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ./predictions.db:/app/predictions.db
      - ./Discord-Bot-WebUI/instance/firebase-service-account.json:/app/instance/firebase-service-account.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webui.rule=Host(`portal.ecsfc.com`)"
      - "traefik.http.routers.webui.entrypoints=web"
      - "traefik.http.routers.webui-secure.entrypoints=websecure"
      - "traefik.http.routers.webui-secure.rule=Host(`portal.ecsfc.com`)"
      - "traefik.http.routers.webui-secure.tls=true"
      - "traefik.http.routers.webui-secure.tls.certresolver=myresolver"
      # HTTPS redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      # Rate limiting middleware
      - "traefik.http.middlewares.rate-limit.ratelimit.average=100"
      - "traefik.http.middlewares.rate-limit.ratelimit.period=1m"
      - "traefik.http.middlewares.rate-limit.ratelimit.burst=50"
      # Security headers
      - "traefik.http.middlewares.secure-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.secure-headers.headers.customresponseheaders.X-Robots-Tag=noindex,nofollow"
      - "traefik.http.middlewares.secure-headers.headers.customresponseheaders.X-Content-Type-Options=nosniff"
      # Apply middlewares  
      - "traefik.http.routers.webui.middlewares=redirect-to-https,rate-limit"
      - "traefik.http.routers.webui-secure.middlewares=secure-headers,rate-limit"
    depends_on:
      redis:
        condition: service_healthy
      pgbouncer:
        condition: service_healthy
    networks:
      - web
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 500M

  flower:
    image: mher/flower
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    environment:
      - FLOWER_UNAUTHENTICATED_API=true
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
      pgbouncer:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flower.rule=Host(`flower.ecsfc.com`)"
      - "traefik.http.routers.flower.entrypoints=web"
      - "traefik.http.routers.flower.middlewares=${TRAEFIK_HTTP_MIDDLEWARES:-}"
      - "traefik.http.routers.flower-secure.entrypoints=websecure"
      - "traefik.http.routers.flower-secure.rule=Host(`flower.ecsfc.com`)"
      - "traefik.http.routers.flower-secure.tls=true"
      - "traefik.http.routers.flower-secure.tls.certresolver=myresolver"
    networks:
      - web

  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - BOT_RESTART_ATTEMPT=0  # Track restart attempts
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy
      pgbouncer:
        condition: service_healthy
      webui:
        condition: service_healthy
    command: python ECS_Discord_Bot.py
    # Add restart policy with a delay to prevent rapid restarts
    restart: unless-stopped
    # Add healthcheck to monitor the bot's health
    healthcheck:
      test: ["CMD", "sh", "-c", "netstat -tulpn | grep -q ':500[0-9] ' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - web
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  web:
    external: true

volumes:
  redis_data:
  celery_data:
  celery_live_data:
  celery_beat_data:
  celery_sync_data:
  celery_enterprise_data: