"""Add is_current column to Season model

Revision ID: 01785a473322
Revises: bee708d1a1c2
Create Date: 2024-09-03 10:37:47.921941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01785a473322'
down_revision = 'bee708d1a1c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_current', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###

    # Optional: Remove server_default if you want to make it truly not nullable without defaults after creation
    op.alter_column('season', 'is_current', server_default=None)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.drop_column('is_current')
    # ### end Alembic commands ###


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.drop_column('is_current')

    # ### end Alembic commands ###
