"""Add relationships between League, Team, and Player

Revision ID: 0af04b9ebfef
Revises: 28ad22354429
Create Date: 2024-08-21 16:15:33.647534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0af04b9ebfef'
down_revision = '28ad22354429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('league', schema=None) as batch_op:
        batch_op.drop_constraint('league_season_id_fkey', type_='foreignkey')
        batch_op.drop_column('season_id')

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'team', ['team_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('team_id')

    with op.batch_alter_table('league', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('league_season_id_fkey', 'season', ['season_id'], ['id'])

    op.drop_table('team')
    # ### end Alembic commands ###
