"""Add account settings fields to User model

Revision ID: 21771f9150fd
Revises: a2fc1ca788d9
Create Date: 2024-09-11 10:47:18.093168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21771f9150fd'
down_revision = 'a2fc1ca788d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sms_notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('discord_notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('profile_visibility', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_visibility')
        batch_op.drop_column('discord_notifications')
        batch_op.drop_column('sms_notifications')
        batch_op.drop_column('email_notifications')

    # ### end Alembic commands ###
