"""Add is_current_player field to Player model

Revision ID: 22087fcb9b47
Revises: cf6ee35c0301
Create Date: 2024-08-22 18:55:28.043370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22087fcb9b47'
down_revision = 'cf6ee35c0301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_current_player', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('is_current_player')

    # ### end Alembic commands ###
