"""Add 2FA fields to users

Revision ID: 26b5ff9fb5c5
Revises: 856c4ddef2fd
Create Date: 2024-09-18 16:11:14.798595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26b5ff9fb5c5'
down_revision = '856c4ddef2fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_2fa_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('totp_secret')
        batch_op.drop_column('is_2fa_enabled')

    # ### end Alembic commands ###
