"""Change discord to bigint

Revision ID: 30180b166431
Revises: a9e0c83e2430
Create Date: 2024-08-30 11:10:22.802186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30180b166431'
down_revision = 'a9e0c83e2430'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column(
            'discord_coach_role_id',
            existing_type=sa.String(),
            type_=sa.BigInteger(),
            postgresql_using="discord_coach_role_id::bigint"
        )
        batch_op.alter_column(
            'discord_player_role_id',
            existing_type=sa.String(),
            type_=sa.BigInteger(),
            postgresql_using="discord_player_role_id::bigint"
        )
        batch_op.alter_column(
            'discord_channel_id',
            existing_type=sa.String(),
            type_=sa.BigInteger(),
            postgresql_using="discord_channel_id::bigint"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('discord_player_role_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('discord_coach_role_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
