"""Add user_id to Player model and establish relationship

Revision ID: 301fb3305cf1
Revises: 06ba72004faa
Create Date: 2024-08-24 15:35:38.016019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '301fb3305cf1'
down_revision = '06ba72004faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
