"""add orderID for Woo

Revision ID: 333d1c6ab0be
Revises: 812e5b6df6bd
Create Date: 2024-08-28 17:08:14.017927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333d1c6ab0be'
down_revision = '812e5b6df6bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###
