"""Add notification icons

Revision ID: 37d5210f8bd4
Revises: f30c18ea8cbb
Create Date: 2024-09-11 11:53:26.166351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37d5210f8bd4'
down_revision = 'f30c18ea8cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
