"""Add Team model and update relationships

Revision ID: 38397d3a45ed
Revises: c7bc570f6ca6
Create Date: 2024-08-21 16:08:03.012258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38397d3a45ed'
down_revision = 'c7bc570f6ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('player_league_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'team', ['team_id'], ['id'])
        batch_op.drop_column('league_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('player_league_id_fkey', 'league', ['league_id'], ['id'])
        batch_op.drop_column('team_id')

    op.drop_table('team')
    # ### end Alembic commands ###
