"""Add has_skipped_profile_creation to User model

Revision ID: 3da575ea0b38
Revises: 2e6aad92b13f
Create Date: 2024-09-14 18:08:46.749757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da575ea0b38'
down_revision = '2e6aad92b13f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_skipped_profile_creation', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('has_skipped_profile_creation')

    # ### end Alembic commands ###
