"""Add manual tracking fields to Player model

Revision ID: 46194e31a3b4
Revises: 61e58cfad154
Create Date: 2024-08-23 13:56:14.156304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46194e31a3b4'
down_revision = '61e58cfad154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_season_goals', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('manual_season_assists', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('manual_season_yellow_cards', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('manual_season_red_cards', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('manual_career_goals', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('manual_career_assists', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('manual_career_yellow_cards', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('manual_career_red_cards', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('manual_career_red_cards')
        batch_op.drop_column('manual_career_yellow_cards')
        batch_op.drop_column('manual_career_assists')
        batch_op.drop_column('manual_career_goals')
        batch_op.drop_column('manual_season_red_cards')
        batch_op.drop_column('manual_season_yellow_cards')
        batch_op.drop_column('manual_season_assists')
        batch_op.drop_column('manual_season_goals')

    # ### end Alembic commands ###
