"""Initial migration

Revision ID: 48c956a232f0
Revises: cd43a65b4df5
Create Date: 2024-08-21 17:34:00.993373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c956a232f0'
down_revision = 'cd43a65b4df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'league', ['league_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('league_id')

    # ### end Alembic commands ###
