"""Add is_coach field to Player model

Revision ID: 61e58cfad154
Revises: 63c591769b49
Create Date: 2024-08-23 12:38:36.618921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61e58cfad154'
down_revision = '63c591769b49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_coach', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('is_coach')

    # ### end Alembic commands ###
