"""Add PlayerSeasonStats model

Revision ID: 6215a7c2691f
Revises: e1c39fa63abe
Create Date: 2024-08-27 12:41:29.063262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6215a7c2691f'
down_revision = 'e1c39fa63abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('red_cards', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('manual_career_red_cards')
        batch_op.drop_column('manual_season_goals')
        batch_op.drop_column('manual_season_assists')
        batch_op.drop_column('manual_career_goals')
        batch_op.drop_column('manual_career_assists')
        batch_op.drop_column('manual_career_yellow_cards')
        batch_op.drop_column('manual_season_yellow_cards')
        batch_op.drop_column('manual_season_red_cards')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_season_red_cards', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('manual_season_yellow_cards', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('manual_career_yellow_cards', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('manual_career_assists', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('manual_career_goals', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('manual_season_assists', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('manual_season_goals', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('manual_career_red_cards', sa.INTEGER(), autoincrement=False, nullable=True))

    op.drop_table('player_season_stats')
    # ### end Alembic commands ###
