"""Add explicit primaryjoin conditions for relationships

Revision ID: 63c591769b49
Revises: f95c565f87b0
Create Date: 2024-08-23 11:42:13.112659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63c591769b49'
down_revision = 'f95c565f87b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'team', ['opponent'], ['id'])
        batch_op.create_foreign_key(None, 'team', ['team_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
