"""Add career stat override fields to Player model

Revision ID: 7f45bdaef5bc
Revises: 6215a7c2691f
Create Date: 2024-08-27 13:43:19.777540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f45bdaef5bc'
down_revision = '6215a7c2691f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('career_goals_override', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('career_assists_override', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('career_yellow_cards_override', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('career_red_cards_override', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('career_red_cards_override')
        batch_op.drop_column('career_yellow_cards_override')
        batch_op.drop_column('career_assists_override')
        batch_op.drop_column('career_goals_override')

    # ### end Alembic commands ###
