"""Create availability table

Revision ID: 827dcdf5e783
Revises: ca3cfb66c7a3
Create Date: 2024-09-05 09:11:56.539465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827dcdf5e783'
down_revision = 'ca3cfb66c7a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('discord_id', sa.String(length=100), nullable=False),
    sa.Column('response', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('availability')
    # ### end Alembic commands ###
