"""Add league_id foreign key to User model

Revision ID: 856c4ddef2fd
Revises: 3da575ea0b38
Create Date: 2024-09-17 14:42:21.104780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856c4ddef2fd'
down_revision = '3da575ea0b38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'league', ['league_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('league_id')

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
