"""Create YellowCard table

Revision ID: 8daf73a00c29
Revises: 6d9c376919f2
Create Date: 2024-08-23 11:32:48.104035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8daf73a00c29'
down_revision = '6d9c376919f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yellow_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['schedule.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('yellow_cards')

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_constraint('schedule_opponent_fkey', type_='foreignkey')
        batch_op.drop_constraint('schedule_team_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.create_foreign_key('schedule_team_id_fkey', 'team', ['team_id'], ['id'])
        batch_op.create_foreign_key('schedule_opponent_fkey', 'team', ['opponent'], ['id'])

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yellow_cards', sa.INTEGER(), autoincrement=False, nullable=True))

    op.drop_table('yellow_card')
    # ### end Alembic commands ###
