"""Add message ID fields to Match model

Revision ID: a2fc1ca788d9
Revises: 827dcdf5e783
Create Date: 2024-09-06 21:41:48.831589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2fc1ca788d9'
down_revision = '827dcdf5e783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_team_message_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('away_team_message_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_column('away_team_message_id')
        batch_op.drop_column('home_team_message_id')

    # ### end Alembic commands ###
