"""Add new fields to Player model for additional player information

Revision ID: a99dd027c226
Revises: 301fb3305cf1
Create Date: 2024-08-24 18:36:37.863491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a99dd027c226'
down_revision = '301fb3305cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pronouns', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('expected_weeks_available', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unavailable_dates', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('willing_to_referee', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('favorite_position', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('other_positions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('positions_not_to_play', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('frequency_play_goal', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('additional_info', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('additional_info')
        batch_op.drop_column('frequency_play_goal')
        batch_op.drop_column('positions_not_to_play')
        batch_op.drop_column('other_positions')
        batch_op.drop_column('favorite_position')
        batch_op.drop_column('willing_to_referee')
        batch_op.drop_column('unavailable_dates')
        batch_op.drop_column('expected_weeks_available')
        batch_op.drop_column('pronouns')
        batch_op.drop_column('player_notes')

    # ### end Alembic commands ###
