"""Add more discord tracking to Team model

Revision ID: a9e0c83e2430
Revises: fd9d1e5510c7
Create Date: 2024-08-30 10:07:09.099911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e0c83e2430'
down_revision = 'fd9d1e5510c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discord_coach_role_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('discord_player_role_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('discord_player_role_id')
        batch_op.drop_column('discord_coach_role_id')

    # ### end Alembic commands ###
