"""Add foreign key to Player

Revision ID: b68cd4bb6445
Revises: bb99e4471847
Create Date: 2024-08-21 15:36:15.036902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68cd4bb6445'
down_revision = 'bb99e4471847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_constraint('league_season_id_fkey', type_='foreignkey')
        batch_op.drop_column('season_id')

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('jersey_size',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               nullable=True)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('jersey_size',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('league', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('league_season_id_fkey', 'season', ['season_id'], ['id'])
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
