"""allow nullable minutes

Revision ID: bbd5d1242b49
Revises: 9485db2aa718
Create Date: 2024-08-29 14:17:19.748856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbd5d1242b49'
down_revision = '9485db2aa718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assist', schema=None) as batch_op:
        batch_op.alter_column('minute',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.alter_column('minute',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('red_card', schema=None) as batch_op:
        batch_op.alter_column('minute',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('yellow_card', schema=None) as batch_op:
        batch_op.alter_column('minute',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yellow_card', schema=None) as batch_op:
        batch_op.alter_column('minute',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('red_card', schema=None) as batch_op:
        batch_op.alter_column('minute',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.alter_column('minute',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('assist', schema=None) as batch_op:
        batch_op.alter_column('minute',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
