"""Add league_type to Season model

Revision ID: bee708d1a1c2
Revises: 30180b166431
Create Date: 2024-09-03 08:44:20.058419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bee708d1a1c2'
down_revision = '30180b166431'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('season', schema=None) as batch_op:
        # Add the new column as nullable initially
        batch_op.add_column(sa.Column('league_type', sa.String(length=50), nullable=True))
    
    # Update the column after it's been added
    op.execute("UPDATE season SET league_type = 'Pub League'")

    with op.batch_alter_table('season', schema=None) as batch_op:
        # Alter the column to be non-nullable
        batch_op.alter_column('league_type', existing_type=sa.String(length=50), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.drop_column('league_type')

    # ### end Alembic commands ###
