"""Add jersey_number to Player model

Revision ID: c168c2ccee29
Revises: 3ba18f114147
Create Date: 2024-09-12 10:10:19.300868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c168c2ccee29'
down_revision = '3ba18f114147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jersey_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('jersey_number')

    # ### end Alembic commands ###
