"""Add goal_difference column to Standings

Revision ID: ca3cfb66c7a3
Revises: ff698b50e9f1
Create Date: 2024-09-04 12:56:19.731400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca3cfb66c7a3'
down_revision = 'ff698b50e9f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_difference', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standings', schema=None) as batch_op:
        batch_op.drop_column('goal_difference')

    # ### end Alembic commands ###
