"""Add stats and notes to Player model

Revision ID: db7f126ec952
Revises: 48c956a232f0
Create Date: 2024-08-22 18:04:24.514014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db7f126ec952'
down_revision = '48c956a232f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goals', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assists', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('yellow_cards', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('red_cards', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('red_cards')
        batch_op.drop_column('yellow_cards')
        batch_op.drop_column('assists')
        batch_op.drop_column('goals')

    # ### end Alembic commands ###
