"""Change columns to Text type

Revision ID: dd4ff4b13997
Revises: 9e6a46d6beae
Create Date: 2024-08-26 12:53:48.562766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4ff4b13997'
down_revision = '9e6a46d6beae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.alter_column('favorite_position',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('manual_season_goals',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('manual_season_assists',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('manual_season_yellow_cards',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('manual_season_red_cards',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.alter_column('manual_season_red_cards',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('manual_season_yellow_cards',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('manual_season_assists',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('manual_season_goals',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('favorite_position',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
