"""Add team_swap column to Player model

Revision ID: e1c39fa63abe
Revises: 988f5a6fe074
Create Date: 2024-08-26 14:47:23.687004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c39fa63abe'
down_revision = '988f5a6fe074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_swap', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('team_swap')

    # ### end Alembic commands ###
