"""Add user_id foreign key to Player model

Revision ID: f77382446ece
Revises: f96416ba63bc
Create Date: 2024-08-28 13:36:47.541981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f77382446ece'
down_revision = 'f96416ba63bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discord_id', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['discord_id'])
        batch_op.drop_column('career_goals_adjustment')
        batch_op.drop_column('career_yellow_cards_adjustment')
        batch_op.drop_column('career_assists_adjustment')
        batch_op.drop_column('career_red_cards_adjustment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('career_red_cards_adjustment', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('career_assists_adjustment', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('career_yellow_cards_adjustment', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('career_goals_adjustment', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('discord_id')

    # ### end Alembic commands ###
