"""Refactor models to use back_populates

Revision ID: f95c565f87b0
Revises: 8daf73a00c29
Create Date: 2024-08-23 11:40:48.358494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f95c565f87b0'
down_revision = '8daf73a00c29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['schedule.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['schedule.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('red_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['schedule.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('goals')
        batch_op.drop_column('red_cards')
        batch_op.drop_column('assists')

    with op.batch_alter_table('yellow_card', schema=None) as batch_op:
        batch_op.alter_column('minute',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yellow_card', schema=None) as batch_op:
        batch_op.alter_column('minute',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assists', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('red_cards', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('goals', sa.INTEGER(), autoincrement=False, nullable=True))

    op.drop_table('red_card')
    op.drop_table('goal')
    op.drop_table('assist')
    # ### end Alembic commands ###
