"""Add discord_channel_id to Team model

Revision ID: fd9d1e5510c7
Revises: bbd5d1242b49
Create Date: 2024-08-30 09:47:09.161197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd9d1e5510c7'
down_revision = 'bbd5d1242b49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discord_channel_id', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('discord_channel_id')

    # ### end Alembic commands ###
