version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/test_db
      - REDIS_URL=redis://redis:6379/15
      - TESTING=true
      - SECRET_KEY=test-secret-key
      - JWT_SECRET_KEY=test-jwt-secret
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.pytest_cache
    depends_on:
      - db
      - redis
    command: pytest -v --cov=app --cov-report=html --cov-report=term

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"  # Different port to avoid conflicts

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"  # Different port to avoid conflicts