# app/pub_league/services.py

"""
Pub League Order Services

This module provides business logic for the Pub League order linking flow:
- PubLeagueOrderService: Order verification, linking, and pass management
- PlayerActivationService: Player status updates and activation
- RoleSyncService: Flask + Discord role synchronization
- ProfileConflictService: Detect and resolve profile conflicts
"""

import hashlib
import hmac
import logging
import re
from datetime import datetime, timedelta
from typing import Any, Optional

import requests
from flask import current_app, g, url_for

from app.core import db
from app.models import (
    Player, Role, Season, User, WalletPass,
    PubLeagueOrder, PubLeagueOrderLineItem, PubLeagueOrderClaim,
    PubLeagueOrderStatus, PubLeagueLineItemStatus, PubLeagueClaimStatus,
    create_pub_league_pass
)
from app.order_helpers import extract_jersey_size_from_product_name, extract_season_name
from app.utils.user_locking import lock_user_for_role_update, LockAcquisitionError
from app.utils.deferred_discord import DeferredDiscordQueue
from app.forms import (
    soccer_positions, goal_frequency_choices, availability_choices,
    pronoun_choices, willing_to_referee_choices
)
from app.constants.positions import (
    normalize_position, parse_positions, format_positions,
)

logger = logging.getLogger(__name__)


# Division to role mapping
DIVISION_ROLES = {
    'Classic': 'pl-classic',
    'Premier': 'pl-premier',
}

# REMOVED: Hardcoded division to league ID mapping
# Previously: DIVISION_LEAGUE_IDS = {'Classic': 11, 'Premier': 10}
# This caused players to be assigned to old season leagues.
# Now using dynamic lookup via SeasonSyncService.get_current_league_id_for_division()


class PubLeagueOrderService:
    """
    Service for managing Pub League order linking.

    Handles order verification, fetching from WooCommerce,
    pass assignment, and claim link management.
    """

    @staticmethod
    def verify_order_token(order_id: int, token: str) -> bool:
        """
        Verify that the token matches the order.

        The token is generated by the WooCommerce plugin using HMAC-SHA256
        with a shared secret.

        Args:
            order_id: WooCommerce order ID
            token: Verification token from URL

        Returns:
            True if token is valid, False otherwise
        """
        secret = current_app.config.get('WALLET_WEBHOOK_SECRET', '')
        if not secret:
            logger.warning("WALLET_WEBHOOK_SECRET not configured")
            return False

        # Generate expected token
        message = f"pub_league_order_{order_id}"
        expected_token = hmac.new(
            secret.encode('utf-8'),
            message.encode('utf-8'),
            hashlib.sha256
        ).hexdigest()

        is_valid = hmac.compare_digest(token, expected_token)

        if not is_valid:
            logger.warning(
                f"Token verification failed for order {order_id}. "
                f"Received token: {token[:16]}... "
                f"Expected token: {expected_token[:16]}... "
                f"Secret configured: {bool(secret)} (length: {len(secret)})"
            )

        return is_valid

    @staticmethod
    def fetch_order_from_woocommerce(order_id: int) -> Optional[dict]:
        """
        Fetch order details from WooCommerce API.

        Args:
            order_id: WooCommerce order ID

        Returns:
            Order data dictionary or None if not found
        """
        try:
            from woocommerce import API

            wcapi = API(
                url=current_app.config['WOO_API_URL'],
                consumer_key=current_app.config['WOO_CONSUMER_KEY'],
                consumer_secret=current_app.config['WOO_CONSUMER_SECRET'],
                version="wc/v3"
            )

            response = wcapi.get(f"orders/{order_id}")
            response.raise_for_status()

            order_data = response.json()

            # Validate order status (must be paid)
            if order_data.get('status') not in ['processing', 'completed']:
                logger.warning(f"Order {order_id} has status {order_data.get('status')}, not valid for linking")
                return None

            return order_data

        except Exception as e:
            logger.error(f"Error fetching order {order_id} from WooCommerce: {e}")
            return None

    @staticmethod
    def extract_pub_league_items(order_data: dict) -> list[dict]:
        """
        Extract Pub League line items from WooCommerce order data.

        Filters for Pub League products and extracts division and jersey size.

        Args:
            order_data: WooCommerce order data

        Returns:
            List of extracted line item data
        """
        pub_league_items = []

        # Pattern to match Pub League products
        pub_league_pattern = re.compile(
            r'(\d{4})\s+(Spring|Fall)\s+ECS\s+Pub\s+League.*?(Classic|Premier)',
            re.IGNORECASE
        )
        alt_pattern = re.compile(
            r'(Spring|Fall)\s+(\d{4})\s+ECS\s+Pub\s+League.*?(Classic|Premier)',
            re.IGNORECASE
        )

        for item in order_data.get('line_items', []):
            product_name = item.get('name', '')
            quantity = item.get('quantity', 1)

            # Check if this is a Pub League product
            match = pub_league_pattern.search(product_name)
            if not match:
                match = alt_pattern.search(product_name)

            if match:
                # Extract division
                division = match.group(3).capitalize()

                # Extract jersey size from product name (last token after " - ")
                jersey_size = extract_jersey_size_from_product_name(product_name)
                if jersey_size == 'N/A':
                    jersey_size = None

                # Create one entry per quantity
                for _ in range(quantity):
                    pub_league_items.append({
                        'woo_line_item_id': item.get('id'),
                        'product_name': product_name,
                        'division': division,
                        'jersey_size': jersey_size,
                    })

        return pub_league_items

    @staticmethod
    def create_or_get_order(woo_order_id: int, order_data: dict) -> PubLeagueOrder:
        """
        Create a new PubLeagueOrder or return existing one.

        Args:
            woo_order_id: WooCommerce order ID
            order_data: WooCommerce order data

        Returns:
            PubLeagueOrder instance
        """
        session = getattr(g, 'db_session', db.session)

        # Query through the SAME session we commit below. `Model.query` binds to
        # Flask-SQLAlchemy's db.session, which in this app is a DIFFERENT session
        # from g.db_session (see app/init/database.py: SessionLocal is its own
        # sessionmaker) — loading here and committing there silently drops writes.
        existing = session.query(PubLeagueOrder).filter_by(woo_order_id=woo_order_id).first()
        if existing:
            return existing

        # Extract billing info
        billing = order_data.get('billing', {})
        customer_name = f"{billing.get('first_name', '')} {billing.get('last_name', '')}".strip()
        customer_email = billing.get('email', '')

        # Extract season from first Pub League item
        pub_league_items = PubLeagueOrderService.extract_pub_league_items(order_data)
        season_name = None
        if pub_league_items:
            season_name = extract_season_name(pub_league_items[0]['product_name'])

        # Find season in database. MUST scope by league_type: Pub League and
        # ECS FC each create a Season row with the SAME name (e.g. "2026 Fall")
        # and both are is_current=True, so an unqualified name lookup returns
        # whichever has the lower PK — often the ECS FC season. That would bind a
        # paid Pub League order to the ECS FC season, making it vanish from the
        # admin "current" view and minting the wallet pass against the wrong
        # season's dates/label.
        season = None
        if season_name:
            session = getattr(g, 'db_session', db.session)
            season = session.query(Season).filter_by(
                name=season_name, league_type='Pub League'
            ).first()

        # Create order
        order = PubLeagueOrder(
            woo_order_id=woo_order_id,
            verification_token=PubLeagueOrder.generate_verification_token(),
            customer_email=customer_email,
            customer_name=customer_name,
            season_name=season_name,
            season_id=season.id if season else None,
            total_passes=len(pub_league_items),
            woo_order_data=order_data,
            expires_at=datetime.utcnow() + timedelta(days=30)  # Order linking expires in 30 days
        )

        session = getattr(g, 'db_session', db.session)
        session.add(order)
        session.flush()  # Get the ID

        # Create line items
        for item_data in pub_league_items:
            line_item = PubLeagueOrderLineItem(
                order_id=order.id,
                woo_line_item_id=item_data['woo_line_item_id'],
                product_name=item_data['product_name'],
                division=item_data['division'],
                jersey_size=item_data['jersey_size'],
            )
            session.add(line_item)

        session.commit()
        return order

    @staticmethod
    def link_pass_to_player(line_item: PubLeagueOrderLineItem, player: Player, user: User = None) -> None:
        """
        Link a line item (pass) to a player.

        Args:
            line_item: PubLeagueOrderLineItem to assign
            player: Player to assign the pass to
            user: Optional User associated with the player
        """
        line_item.assign_to_player(player, user)

        session = getattr(g, 'db_session', db.session)
        session.commit()

        logger.info(f"Linked line item {line_item.id} to player {player.id} ({player.name})")

    @staticmethod
    def create_claim_link(
        order: PubLeagueOrder,
        line_item: PubLeagueOrderLineItem,
        created_by_user: User,
        recipient_email: str = None,
        recipient_name: str = None
    ) -> PubLeagueOrderClaim:
        """
        Create a claim link for an unassigned pass.

        Args:
            order: PubLeagueOrder
            line_item: PubLeagueOrderLineItem to create claim for
            created_by_user: User creating the claim link
            recipient_email: Optional email to send claim link to
            recipient_name: Optional name of recipient

        Returns:
            PubLeagueOrderClaim instance
        """
        claim = PubLeagueOrderClaim.create_claim(
            order=order,
            line_item=line_item,
            created_by_user=created_by_user,
            recipient_email=recipient_email,
            recipient_name=recipient_name,
            expiry_days=7
        )

        session = getattr(g, 'db_session', db.session)
        session.add(claim)
        session.commit()

        logger.info(f"Created claim link {claim.claim_token[:8]}... for line item {line_item.id}")
        return claim

    @staticmethod
    def process_claim(claim_token: str, player: Player, user: User) -> PubLeagueOrderLineItem:
        """
        Process a claim - assign the pass to the claiming player.

        Args:
            claim_token: The claim token from the URL
            player: Player claiming the pass
            user: User claiming the pass

        Returns:
            The assigned line item

        Raises:
            ValueError: If claim is invalid or expired
        """
        session = getattr(g, 'db_session', db.session)

        # Load through the session we commit. `PubLeagueOrderClaim.find_by_token`
        # goes via Model.query -> Flask-SQLAlchemy's db.session, which is NOT
        # g.db_session here, so the CLAIMED status flip and the line-item
        # assignment would be made on one session and committed on another —
        # i.e. rolled back at teardown, leaving the claim link reusable.
        claim = session.query(PubLeagueOrderClaim).filter_by(claim_token=claim_token).first()
        if not claim:
            raise ValueError("Invalid claim link")

        if not claim.is_valid():
            session.commit()  # persist a PENDING -> EXPIRED transition
            raise ValueError("This claim link has expired or already been used")

        claim.process_claim(player, user)
        session.commit()

        logger.info(f"Claim {claim_token[:8]}... processed for player {player.id}")
        return claim.line_item

    @staticmethod
    def generate_wallet_pass_for_line_item(line_item: PubLeagueOrderLineItem) -> WalletPass:
        """
        Generate a wallet pass for an assigned line item.

        Args:
            line_item: The assigned line item

        Returns:
            WalletPass instance

        Raises:
            ValueError: If line item is not properly assigned
        """
        if not line_item.assigned_player_id:
            raise ValueError("Line item is not assigned to a player")

        player = line_item.assigned_player
        order = line_item.order
        season = order.season

        if not season:
            # Fall back to season_name — scoped to Pub League, since ECS FC has a
            # same-named current season and an unqualified lookup could mint this
            # pass against the wrong season. (order.season above is trustworthy
            # once create_or_get_order sets season_id correctly, which it now does.)
            session = getattr(g, 'db_session', db.session)
            season = session.query(Season).filter_by(
                name=order.season_name, league_type='Pub League'
            ).first()

        if not season:
            raise ValueError("Could not determine season for pass creation")

        # Create the pass
        wallet_pass = create_pub_league_pass(
            player=player,
            season=season,
            woo_order_id=order.woo_order_id
        )

        session = getattr(g, 'db_session', db.session)
        session.add(wallet_pass)
        session.flush()

        # Update line item
        line_item.mark_pass_created(wallet_pass)
        session.commit()

        logger.info(f"Created wallet pass {wallet_pass.id} for line item {line_item.id}")
        return wallet_pass


class PlayerActivationService:
    """
    Service for activating players after Pub League order linking.

    Handles setting is_current_player, updating league assignment,
    and coordinating role sync.
    """

    @staticmethod
    def activate_player_for_league(
        player: Player,
        user: User,
        division: str,
        jersey_size: str = None
    ) -> None:
        """
        Activate a player for a Pub League division.

        1. Set player.is_current_player = True
        2. Update player.jersey_size if provided (from conflict resolution)
        3. Update player.league_id based on division (using current season lookup)
        4. Sync roles (Flask + Discord) via RoleSyncService
        5. Invalidate draft cache to ensure player appears immediately

        Args:
            player: Player to activate
            user: User associated with the player
            division: 'Classic' or 'Premier'
            jersey_size: Optional jersey size to update
        """
        from app.services.season_sync_service import SeasonSyncService

        session = getattr(g, 'db_session', db.session)

        # 1. Set is_current_player
        player.is_current_player = True

        # 2. Update jersey size if provided
        if jersey_size:
            player.jersey_size = jersey_size

        # 3. Update league assignment using DYNAMIC current season lookup
        # This replaces the old hardcoded DIVISION_LEAGUE_IDS mapping
        current_league = SeasonSyncService.get_current_league_by_name(session, division)
        if current_league:
            player.league_id = current_league.id
            player.primary_league_id = current_league.id
            logger.info(f"Assigned player {player.id} to current season league {current_league.id} ({division})")
        else:
            logger.warning(f"Could not find current season league for division '{division}'")

        session.commit()

        # 4. Sync roles (only if user exists and is approved)
        if user and hasattr(user, 'is_approved') and user.is_approved:
            RoleSyncService.sync_league_role(user, player, division)

        # 5. Invalidate draft cache so player appears immediately
        try:
            from app.draft_cache_service import DraftCacheService
            DraftCacheService.clear_all_league_caches(division.lower())
            logger.info(f"Cleared draft cache for {division} after activating player {player.id}")
        except Exception as e:
            logger.warning(f"Could not clear draft cache after player activation: {e}")

        logger.info(f"Activated player {player.id} for {division} division")

    @staticmethod
    def deactivate_player_if_no_current_pass(
        player_id: int, order, exclude_line_item_id: int = None
    ) -> bool:
        """
        Counterpart to activation: when a player loses a pass (unassign /
        reassign-away), drop is_current_player — UNLESS they still hold another
        pass for the SAME season.

        is_current_player means "paid/active THIS season" and is set ONLY by
        linking a pass; season rollover clears it for everyone and they
        re-activate on purchase (see season_routes.py). So removing their last
        current-season pass should return them to not-current, mirroring rollover.

        The guard matters: a player can hold two passes for one season (e.g. they
        bought Premier and were gifted Classic). Unassigning one must NOT
        deactivate them while the other still stands. We deliberately touch ONLY
        is_current_player — not their Discord role or league_id — because that's
        the single axis "am I paid for this season," matching how rollover works.

        Args:
            player_id: the player losing the pass
            order: the PubLeagueOrder the removed line item belonged to (for its season)
            exclude_line_item_id: the line item being removed, excluded from the count

        Returns:
            True if the player was deactivated, False if they kept another pass
            (or had no player row / no season to scope by).
        """
        if not player_id or order is None:
            return False

        session = getattr(g, 'db_session', db.session)

        # Any OTHER still-held pass for this same season keeps them current.
        # "held" = assigned / claimed / pass_created (PubLeagueOrderLineItem.is_assigned()).
        held_statuses = [
            PubLeagueLineItemStatus.ASSIGNED.value,
            PubLeagueLineItemStatus.CLAIMED.value,
            PubLeagueLineItemStatus.PASS_CREATED.value,
        ]
        q = (
            session.query(PubLeagueOrderLineItem)
            .join(PubLeagueOrder, PubLeagueOrderLineItem.order_id == PubLeagueOrder.id)
            .filter(
                PubLeagueOrderLineItem.assigned_player_id == player_id,
                PubLeagueOrderLineItem.status.in_(held_statuses),
            )
        )
        # Scope to the same season. Prefer season_id; fall back to season_name so
        # an order that never got its season_id backfilled still scopes sanely.
        if order.season_id is not None:
            q = q.filter(PubLeagueOrder.season_id == order.season_id)
        elif order.season_name:
            q = q.filter(PubLeagueOrder.season_name == order.season_name)
        if exclude_line_item_id is not None:
            q = q.filter(PubLeagueOrderLineItem.id != exclude_line_item_id)

        if q.first() is not None:
            logger.info(
                f"Player {player_id} keeps is_current_player: still holds another "
                f"pass for season {order.season_name or order.season_id}"
            )
            return False

        player = session.query(Player).get(player_id)
        if not player:
            return False

        if player.is_current_player:
            player.is_current_player = False
            session.commit()
            logger.info(
                f"Deactivated player {player_id} (is_current_player=False): last "
                f"pass for season {order.season_name or order.season_id} removed"
            )
            # Draft rosters filter on is_current_player — refresh so they drop off.
            try:
                from app.draft_cache_service import DraftCacheService
                DraftCacheService.clear_all_league_caches('classic')
                DraftCacheService.clear_all_league_caches('premier')
            except Exception as exc:
                logger.warning(f"Could not clear draft cache after deactivation: {exc}")
        return True

    @staticmethod
    def check_profile_freshness(player: Player, days: int = 60) -> bool:
        """
        Check if player's profile was updated within the specified days.

        Args:
            player: Player to check
            days: Number of days to consider "fresh" (default 60)

        Returns:
            True if profile is fresh (updated within days), False otherwise
        """
        if not player.profile_last_updated:
            return False

        threshold = datetime.utcnow() - timedelta(days=days)
        return player.profile_last_updated > threshold

    # Fields we consider load-bearing for a "complete" Pub League profile.
    # A player missing any of these should be routed through the full,
    # forced profile review (not the compact one-tap confirm).
    PROFILE_KEY_FIELDS = ('jersey_size', 'favorite_position', 'expected_weeks_available')

    @staticmethod
    def profile_is_complete(player: Player) -> bool:
        """
        Determine whether the player has filled in the key details we need.

        This is deliberately stricter than freshness: a profile can be
        recently touched but still be missing the fields coaches and admins
        rely on. Missing any key field means the player must go through the
        full profile review rather than the compact confirm.

        Args:
            player: Player to check

        Returns:
            True if all key fields (and a phone number) are set.
        """
        if not player:
            return False

        for field in PlayerActivationService.PROFILE_KEY_FIELDS:
            if not getattr(player, field, None):
                return False

        # Phone lives in an encrypted column; check the raw column so we
        # don't pay for a decrypt just to test presence.
        if not getattr(player, 'encrypted_phone', None):
            return False

        return True

    @staticmethod
    def profile_needs_full_review(player: Player) -> bool:
        """
        True when the player should be forced through the multi-section
        profile review (new / incomplete / stale), False when a compact
        one-tap confirm is enough (complete AND fresh).

        Args:
            player: Player to evaluate (may be None for a brand-new buyer)

        Returns:
            True if the full review should be forced.
        """
        if not player:
            return True

        if not PlayerActivationService.profile_is_complete(player):
            return True

        # Complete but stale -> still make them read it.
        return not PlayerActivationService.check_profile_freshness(player)

    @staticmethod
    def ensure_player_for_user(user: User, order_data: dict = None) -> Player:
        """
        Guarantee the logged-in user has a Player record so the purchase /
        link flow never dead-ends on "No player profile found".

        Most buyers arrive here after Discord OAuth, which already creates a
        Player. This is the safety net for the rare case where a user reaches
        pass assignment with no Player: we create a minimal one (name pulled
        from the order billing name, falling back to their username) linked to
        their account, so they can flow straight into profile confirmation.

        Args:
            user: The authenticated User (must be a real, session-bound model)
            order_data: Optional WooCommerce order data to source a name from

        Returns:
            The existing or newly created Player.
        """
        existing = getattr(user, 'player', None)
        if existing:
            return existing

        session = getattr(g, 'db_session', db.session)

        # Prefer the name from the order's billing details, then the username.
        name = None
        if order_data:
            billing = order_data.get('billing', {}) or {}
            first = (billing.get('first_name') or '').strip()
            last = (billing.get('last_name') or '').strip()
            name = f"{first} {last}".strip() or None
        if not name:
            name = (getattr(user, 'username', None) or '').strip() or 'New Player'

        player = Player(
            name=name[:100],
            user_id=user.id,
            is_current_player=False,
            profile_last_updated=datetime.utcnow(),
        )
        session.add(player)
        session.commit()

        logger.info(f"Created minimal Player {player.id} for user {user.id} during pass linking")
        return player


class RoleSyncService:
    """
    Service for syncing league roles in both Flask and Discord.

    ONLY manages pl-classic and pl-premier roles.
    All other roles (admin, coach, ref, team) are NEVER touched.
    """

    @staticmethod
    def sync_league_role(user: User, player: Player, new_division: str) -> None:
        """
        Sync league role in BOTH Flask and Discord.

        Only manages pl-classic and pl-premier roles.
        If switching leagues (Classic <-> Premier), removes old role and adds new.

        Args:
            user: User to update roles for
            player: Player associated with user (for Discord sync)
            new_division: 'Classic' or 'Premier'
        """
        new_role_name = DIVISION_ROLES.get(new_division)
        if not new_role_name:
            logger.warning(f"Unknown division: {new_division}")
            return

        opposite_division = 'Premier' if new_division == 'Classic' else 'Classic'
        opposite_role_name = DIVISION_ROLES.get(opposite_division)

        # 1. Flask role sync (database)
        RoleSyncService._sync_flask_role(user, new_role_name, opposite_role_name)

        # 2. Mark player for Discord role sync
        # The sync system reads Flask roles and maps them to Discord roles
        RoleSyncService._sync_discord_role(player)

    @staticmethod
    def _sync_flask_role(user: User, new_role_name: str, opposite_role_name: str) -> None:
        """
        Sync Flask roles in the database.

        Uses pessimistic locking to prevent concurrent role modifications.

        Args:
            user: User to update
            new_role_name: Role to add (e.g., 'pl-classic')
            opposite_role_name: Role to remove if present (e.g., 'pl-premier')
        """
        # Save user_id before any session operations to avoid detached instance issues
        user_id = user.id

        try:
            # Acquire lock on user for role modification
            with lock_user_for_role_update(user_id, session=db.session) as locked_user:
                # Get role objects from the same db.session
                new_role = db.session.query(Role).filter_by(name=new_role_name).first()
                opposite_role = db.session.query(Role).filter_by(name=opposite_role_name).first()

                # Add new role if not already present
                if new_role and new_role not in locked_user.roles:
                    locked_user.roles.append(new_role)
                    logger.info(f"Added Flask role {new_role_name} to user {user_id}")

                # Remove opposite role ONLY if they had it (league switch)
                if opposite_role and opposite_role in locked_user.roles:
                    locked_user.roles.remove(opposite_role)
                    logger.info(f"Removed Flask role {opposite_role_name} from user {user_id}")

                db.session.commit()

        except LockAcquisitionError:
            db.session.rollback()
            logger.warning(f"Could not acquire lock for user {user_id} during role sync")
            raise

    @staticmethod
    def _sync_discord_role(player: Player) -> None:
        """
        Mark player for Discord role sync.

        The Discord role sync system reads Flask roles and syncs them to Discord.
        After updating Flask roles (in _sync_flask_role), we mark the player
        for update so the background sync job picks it up.

        Args:
            player: Player to mark for Discord update
        """
        try:
            if not player.discord_id:
                logger.warning(f"Player {player.id} has no Discord ID, skipping Discord role sync")
                return

            # Mark player for Discord update - the sync system will read
            # Flask roles (pl-classic, pl-premier) and map them to Discord roles
            # (ECS-FC-PL-CLASSIC, ECS-FC-PL-PREMIER)
            session = getattr(g, 'db_session', db.session)
            player.discord_needs_update = True
            session.commit()

            logger.info(f"Marked player {player.id} for Discord role sync")

        except Exception as e:
            logger.error(f"Error marking player {player.id} for Discord update: {e}")


class ProfileConflictService:
    """
    Service for detecting and resolving profile conflicts between
    WooCommerce order data and Flask portal profile.

    Portal is the GOLD STANDARD - order data is just a suggestion.
    """

    # Fields to compare for conflicts
    COMPARABLE_FIELDS = {
        'name': 'Name',
        'jersey_size': 'Jersey Size',
        # 'phone': 'Phone',  # Phone comparison requires decryption, skip for now
    }

    @staticmethod
    def detect_conflicts(player: Player, order_data: dict) -> list[dict]:
        """
        Compare order data with player profile to find conflicts.

        Portal is GOLD STANDARD - order data is just a suggestion.

        Args:
            player: Player to compare against
            order_data: WooCommerce order data (or extracted billing/item data)

        Returns:
            List of conflicts, each with:
            - field: Field name (e.g., 'jersey_size')
            - portal_value: Current value in portal
            - order_value: Value from order
            - display_name: Human-readable field name
        """
        conflicts = []
        order_fields = ProfileConflictService._get_comparable_order_fields(order_data)

        for field, display_name in ProfileConflictService.COMPARABLE_FIELDS.items():
            portal_value = getattr(player, field, None)
            order_value = order_fields.get(field)

            # Skip if either value is empty/None
            if not portal_value or not order_value:
                continue

            # Normalize for comparison
            portal_normalized = str(portal_value).strip().lower()
            order_normalized = str(order_value).strip().lower()

            # Check for mismatch
            if portal_normalized != order_normalized:
                conflicts.append({
                    'field': field,
                    'portal_value': portal_value,
                    'order_value': order_value,
                    'display_name': display_name,
                })

        return conflicts

    @staticmethod
    def _get_comparable_order_fields(order_data: dict) -> dict:
        """
        Extract comparable fields from WooCommerce order data.

        Args:
            order_data: WooCommerce order data

        Returns:
            Dictionary of field: value for comparison
        """
        fields = {}

        # Extract name from billing
        billing = order_data.get('billing', {})
        if billing:
            first_name = billing.get('first_name', '')
            last_name = billing.get('last_name', '')
            if first_name or last_name:
                fields['name'] = f"{first_name} {last_name}".strip()

        # Extract jersey size from line items (first Pub League item)
        for item in order_data.get('line_items', []):
            product_name = item.get('name', '')
            if 'Pub League' in product_name:
                jersey_size = extract_jersey_size_from_product_name(product_name)
                if jersey_size and jersey_size != 'N/A':
                    fields['jersey_size'] = jersey_size
                break

        return fields

    @staticmethod
    def resolve_conflict(
        player: Player,
        field: str,
        use_order_value: bool,
        order_value: Any
    ) -> None:
        """
        Apply user's resolution decision for a conflict.

        Args:
            player: Player to update
            field: Field name to potentially update
            use_order_value: True to update player with order value
            order_value: The value from the order
        """
        if not use_order_value:
            # Keep portal value - no action needed
            logger.info(f"Keeping portal value for {field} on player {player.id}")
            return

        # Update player with order value
        if hasattr(player, field):
            setattr(player, field, order_value)

            session = getattr(g, 'db_session', db.session)
            session.commit()

            logger.info(f"Updated player {player.id} {field} to {order_value} (from order)")

    @staticmethod
    def apply_resolutions(player: Player, resolutions: list[dict]) -> None:
        """
        Apply multiple conflict resolutions at once.

        Args:
            player: Player to update
            resolutions: List of resolution decisions, each with:
                - field: Field name
                - use_order_value: Boolean
                - order_value: Value to use if use_order_value is True
        """
        for resolution in resolutions:
            ProfileConflictService.resolve_conflict(
                player=player,
                field=resolution['field'],
                use_order_value=resolution.get('use_order_value', False),
                order_value=resolution.get('order_value')
            )


class ProfileUpdateService:
    """
    Single source of truth for the "confirm your profile" step.

    Both front-ends write the profile through here — the web wizard
    (POST /pub-league/link-order/update-profile) and the app
    (POST /api/v1/pub-league/confirm-profile) — so the two can never drift on
    whitelists, position normalization, or the profile_last_updated stamp.

    Every select value is whitelisted against the canonical form option lists,
    and `form_options()` hands those same lists to the client so the app never
    hardcodes a dropdown that the server would then reject.
    """

    @staticmethod
    def form_options(session, extra_jersey_sizes: list[str] = None) -> dict:
        """
        The option lists a client needs to render the profile-confirm step.

        Jersey sizes mirror the player profile form, which builds its dropdown
        from ``distinct(Player.jersey_size)`` rather than a hardcoded list.
        `extra_jersey_sizes` folds in the size on the order's WooCommerce
        variation so it can prefill even if no existing player has that size.
        """
        rows = session.query(Player.jersey_size).distinct().all()
        sizes = {r[0] for r in rows if r[0]}
        sizes.update(s for s in (extra_jersey_sizes or []) if s)

        def _pairs(choices):
            return [{'value': value, 'label': label} for value, label in choices]

        return {
            'jersey_sizes': sorted(sizes),
            'positions': _pairs(soccer_positions),
            'goal_frequency': _pairs(goal_frequency_choices),
            'availability': _pairs(availability_choices),
            'pronouns': _pairs(pronoun_choices),
            'willing_to_referee': _pairs(willing_to_referee_choices),
        }

    @staticmethod
    def prefill(player: Player, fallback_name: str = '', fallback_jersey_size: str = '') -> dict:
        """Current profile values for the confirm step, in the shape clients post back."""
        return {
            'name': (player.name if player else '') or fallback_name,
            'pronouns': player.pronouns if player else '',
            'phone': (player.phone if player else '') or '',
            'jersey_size': (player.jersey_size if player else '') or fallback_jersey_size,
            'jersey_number': player.jersey_number if player else '',
            'favorite_position': normalize_position(player.favorite_position) if player else '',
            'other_positions': parse_positions(player.other_positions) if player else [],
            'positions_not_to_play': parse_positions(player.positions_not_to_play) if player else [],
            'frequency_play_goal': player.frequency_play_goal if player else '',
            'expected_weeks_available': player.expected_weeks_available if player else '',
            'willing_to_referee': player.willing_to_referee if player else '',
            'player_notes': (player.player_notes if player else '') or '',
        }

    @staticmethod
    def apply(player: Player, data: dict) -> None:
        """
        Persist a confirmed profile payload onto ``player``.

        All fields are optional; anything absent or failing its whitelist is
        left untouched rather than blanked, so a partial payload from an older
        client can never wipe good data. Stamps profile_last_updated so the
        review-due logic resets.
        """
        allowed_positions = {value for value, _ in soccer_positions}
        allowed_goal_frequency = {value for value, _ in goal_frequency_choices}
        allowed_availability = {value for value, _ in availability_choices}
        allowed_pronouns = {value for value, _ in pronoun_choices}
        allowed_referee = {value for value, _ in willing_to_referee_choices}

        # --- Identity & Contact ---
        name = (data.get('name') or '').strip()
        if name:
            player.name = name[:100]

        pronouns = (data.get('pronouns') or '').strip()
        if pronouns in allowed_pronouns:
            player.pronouns = pronouns

        # Phone uses the encrypting setter; only write when a value is given so
        # we don't wipe an existing number on an accidental blank.
        phone = (data.get('phone') or '').strip()
        if phone:
            player.phone = phone[:20]

        # Jersey size mirrors the profile form, which accepts any distinct size
        # in use (not a fixed list). Guard only on column length (String(10)).
        jersey_size = (data.get('jersey_size') or '').strip()
        if jersey_size and len(jersey_size) <= 10:
            player.jersey_size = jersey_size

        jersey_number_raw = data.get('jersey_number')
        if jersey_number_raw not in (None, ''):
            try:
                _jn = int(jersey_number_raw)
                # Range-guard: the column is a 4-byte int; an out-of-range value
                # only fails at commit() and would then lose the WHOLE profile
                # update. Jersey numbers are 0-99.
                if 0 <= _jn <= 99:
                    player.jersey_number = _jn
            except (TypeError, ValueError):
                pass  # ignore non-numeric jersey numbers

        # --- Playing ---
        # Positions are normalized to canonical slugs and stored as {slug,slug}
        # via the single source of truth, so every client writes the same shape.
        favorite_position = normalize_position(data.get('favorite_position'))
        if favorite_position in allowed_positions:
            player.favorite_position = favorite_position

        other_positions = data.get('other_positions')
        if isinstance(other_positions, list):
            player.other_positions = format_positions(other_positions)

        positions_not_to_play = data.get('positions_not_to_play')
        if isinstance(positions_not_to_play, list):
            player.positions_not_to_play = format_positions(positions_not_to_play)

        frequency_play_goal = (data.get('frequency_play_goal') or '').strip()
        if frequency_play_goal in allowed_goal_frequency:
            player.frequency_play_goal = frequency_play_goal

        # --- Availability ---
        expected_weeks_available = (data.get('expected_weeks_available') or '').strip()
        if expected_weeks_available in allowed_availability:
            player.expected_weeks_available = expected_weeks_available

        willing_to_referee = (data.get('willing_to_referee') or '').strip()
        if willing_to_referee in allowed_referee:
            player.willing_to_referee = willing_to_referee

        # Free-text notes for coaches/admins. Present as a key only when the
        # client sends it, so we don't wipe existing notes on older payloads.
        if 'player_notes' in data:
            player.player_notes = (data.get('player_notes') or '').strip()[:2000]

        # Stamp the review so the 5-month "please update" alert resets.
        player.profile_last_updated = datetime.utcnow()

        session = getattr(g, 'db_session', db.session)
        session.commit()


class ProductUrlService:
    """
    Service for generating WooCommerce product URLs for Pub League passes.

    URLs are derived from the CURRENT Pub League season, so a single link (and a
    single printed QR) keeps working across rollovers: scan it in Fall 2026 and
    it resolves to the 2026-fall product; scan the same code next season and it
    resolves to 2027-spring. Nothing to reprint.

    An admin-configured slug OVERRIDES that and is therefore season-frozen — see
    the warning in get_product_url.
    """

    DIVISIONS = ('Classic', 'Premier')

    @staticmethod
    def get_current_season_name() -> Optional[str]:
        """
        Name of the current PUB LEAGUE season (e.g. "2026 Fall").

        Must filter on league_type: Pub League and ECS FC each have their own
        season row and BOTH are is_current=True at the same time, so an
        unqualified is_current lookup can hand back the ECS FC season and build
        a product slug for a product that doesn't exist.
        """
        from app.models import Season
        try:
            session = getattr(g, 'db_session', db.session)
            season = session.query(Season).filter_by(
                league_type='Pub League', is_current=True
            ).first()
            return season.name if season else None
        except Exception as exc:
            logger.warning(f"Could not resolve current Pub League season: {exc}")
            return None

    @staticmethod
    def get_product_url(division: str, season_name: str = None) -> Optional[str]:
        """
        Get the WooCommerce product URL for a division.

        Args:
            division: 'Classic' or 'Premier'
            season_name: Optional season name (e.g. '2026 Fall'). Defaults to the
                        current Pub League season.

        Returns:
            Full product URL, or None if we can't build one (no configured slug
            AND no current season to derive it from). Callers MUST handle None —
            returning a guessed URL would dump a buyer on a 404 at the shop.
        """
        from app.models import AdminConfig

        # Get base shop URL
        shop_url = AdminConfig.get_setting('woocommerce_shop_url', 'https://weareecs.com')
        shop_url = shop_url.rstrip('/')

        # An explicit admin slug wins — but note it does NOT roll over with the
        # season. If one is set, it keeps pointing at the same product forever,
        # which is what you want for a one-off but is a trap across a rollover.
        # ProductUrlService.slug_override_active() surfaces this to the admin UI.
        if division.lower() == 'premier':
            slug = AdminConfig.get_setting('pub_league_premier_product_slug', '')
        else:
            slug = AdminConfig.get_setting('pub_league_classic_product_slug', '')

        if slug:
            return f"{shop_url}/product/{slug}/"

        if not season_name:
            season_name = ProductUrlService.get_current_season_name()

        if season_name:
            # "2026 Fall" (or legacy "Fall 2026") -> 2026-fall-ecs-pub-league-<div>-division.
            # REQUIRE exactly one token to be a 4-digit year and the other to be
            # the season word. Otherwise return None (→ "not on sale") rather than
            # guessing: a name like "Fall Fest" would otherwise build a slug that
            # 404s at the shop, sending a buyer to a dead link at the party.
            parts = season_name.split()
            if len(parts) == 2:
                year = season = None
                for part in parts:
                    if re.fullmatch(r'\d{4}', part):
                        year = part
                    else:
                        season = part.lower()
                if year and season:
                    slug = f"{year}-{season}-ecs-pub-league-{division.lower()}-division"
                    return f"{shop_url}/product/{slug}/"
                logger.warning(
                    f"Season name '{season_name}' isn't '<year> <season>'; "
                    f"cannot build a product URL for {division}."
                )

        return None

    @staticmethod
    def slug_override_active(division: str) -> bool:
        """True when a hardcoded slug is configured for this division.

        Surfaced in the admin QR page: an override means the link is pinned to
        one product and will NOT follow the season rollover.
        """
        from app.models import AdminConfig
        key = ('pub_league_premier_product_slug' if division.lower() == 'premier'
               else 'pub_league_classic_product_slug')
        return bool(AdminConfig.get_setting(key, ''))

    @staticmethod
    def get_buy_options(season_name: str = None) -> list[dict]:
        """
        The divisions a buyer can choose between, with their resolved Woo URLs.

        Shared by the web division-picker page and the app's picker endpoint so
        the two can't disagree about what's on sale.
        """
        if not season_name:
            season_name = ProductUrlService.get_current_season_name()

        options = []
        for division in ProductUrlService.DIVISIONS:
            options.append({
                'division': division.lower(),
                'name': division,
                'season_name': season_name,
                'product_url': ProductUrlService.get_product_url(division, season_name),
                'slug_override': ProductUrlService.slug_override_active(division),
            })
        return options

    @staticmethod
    def get_all_product_urls(season_name: str = None) -> dict:
        """
        Get product URLs for both divisions.

        Args:
            season_name: Optional season name

        Returns:
            Dict with 'premier' and 'classic' URLs
        """
        return {
            'premier': ProductUrlService.get_product_url('Premier', season_name),
            'classic': ProductUrlService.get_product_url('Classic', season_name),
        }


class UserSearchService:
    """
    Service for searching users to assign passes to.

    Searches by name, email, and Discord username.
    """

    @staticmethod
    def search_users(query: str, limit: int = 10) -> list[dict]:
        """
        Search for users by name, email, or Discord username.

        Args:
            query: Search query string
            limit: Maximum number of results

        Returns:
            List of user dictionaries with id, name, email_hint, discord_username
        """
        if not query or len(query) < 2:
            return []

        session = getattr(g, 'db_session', db.session)
        query_lower = query.lower()

        # Search players by name or Discord username
        players = session.query(Player).filter(
            db.or_(
                Player.name.ilike(f'%{query}%'),
                Player.discord_username.ilike(f'%{query}%')
            )
        ).limit(limit).all()

        results = []
        for player in players:
            # Get associated user
            user = player.user if player.user_id else None

            results.append({
                'player_id': player.id,
                'user_id': user.id if user else None,
                'name': player.name,
                'discord_username': player.discord_username,
                'email_hint': ProfileConflictService._mask_email(user.email) if user and hasattr(user, 'email') else None,
                'is_current_player': player.is_current_player,
            })

        return results

    @staticmethod
    def _mask_email(email: str) -> str:
        """
        Mask an email for display (e.g., j***@example.com).

        Args:
            email: Full email address

        Returns:
            Masked email string
        """
        if not email or '@' not in email:
            return None

        local, domain = email.split('@', 1)
        if len(local) <= 2:
            masked_local = local[0] + '*'
        else:
            masked_local = local[0] + '*' * (len(local) - 2) + local[-1]

        return f"{masked_local}@{domain}"
